# Generated by Django 3.0.5 on 2024-01-15 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bazaar', '0010_auto_20211204_1650'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
